/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author YOJHAN DAVID
 */

import adminOp.newproduct;
import adminOp.newWorker;
import adminOp.listWorker;
import adminOp.deleteWorker;

public class adminDash extends javax.swing.JFrame {

    /**
     * Creates new form adminDash
     */
    public adminDash() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        backLogin1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Agregar_trabajo = new javax.swing.JButton();
        Agregar_producto = new javax.swing.JButton();
        Despedir_trabajador = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backLogin1.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        backLogin1.setText("BACK TO LOGINS");
        backLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backLogin1ActionPerformed(evt);
            }
        });
        jPanel2.add(backLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        Agregar_trabajo.setBackground(new java.awt.Color(153, 153, 255));
        Agregar_trabajo.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        Agregar_trabajo.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_trabajo.setText("ADD WORKER");
        Agregar_trabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_trabajoActionPerformed(evt);
            }
        });

        Agregar_producto.setBackground(new java.awt.Color(153, 153, 255));
        Agregar_producto.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        Agregar_producto.setForeground(new java.awt.Color(255, 255, 255));
        Agregar_producto.setText("ADD PRODUCT");
        Agregar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_productoActionPerformed(evt);
            }
        });

        Despedir_trabajador.setBackground(new java.awt.Color(153, 153, 255));
        Despedir_trabajador.setFont(new java.awt.Font("JetBrains Mono", 0, 18)); // NOI18N
        Despedir_trabajador.setForeground(new java.awt.Color(255, 255, 255));
        Despedir_trabajador.setText("DELETE WORKER");
        Despedir_trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Despedir_trabajadorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        jLabel3.setText("CHOOSE AN OPTION");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(Despedir_trabajador))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Agregar_trabajo)
                                .addComponent(Agregar_producto)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(Agregar_trabajo)
                .addGap(39, 39, 39)
                .addComponent(Agregar_producto)
                .addGap(41, 41, 41)
                .addComponent(Despedir_trabajador)
                .addGap(41, 41, 41))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 320));

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel2.setText("IN THIS APART YOU CAN MODIFY AND ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 250, 40));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME ADMIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 656, 160));

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel4.setText("ADD WORKER AND ALL THE GESTION WHAT MEAN OF ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jLabel5.setText("ALL APART OF PRODUC AND WORKERS.");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        Background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Agregar_trabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_trabajoActionPerformed
        // TODO add your handling code here:
        
        newWorker access = new newWorker();
        access.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_Agregar_trabajoActionPerformed

    private void Despedir_trabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Despedir_trabajadorActionPerformed
        // TODO add your handling code here:
        
        listWorker access = new listWorker();
        access.setVisible(true);
        
        deleteWorker access2 = new deleteWorker();
        access2.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_Despedir_trabajadorActionPerformed

    private void Agregar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_productoActionPerformed
        // TODO add your handling code here:
        
        newproduct access = new newproduct();
        access.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_Agregar_productoActionPerformed

    private void backLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backLogin1ActionPerformed
        // TODO add your handling code here:

        loginUser access = new loginUser();
        access.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_backLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_producto;
    private javax.swing.JButton Agregar_trabajo;
    private javax.swing.JPanel Background;
    private javax.swing.JButton Despedir_trabajador;
    private javax.swing.JButton backLogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
